### ISSUE TITLE
tftp does not start

### ISSUE THREAD

**Issue by joda666** [convergeone/freeztp#63]
● ztp.service - FreeZTP Service
   Loaded: loaded (/etc/systemd/system/ztp.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-04-03 18:19:12 CEST; 2min 52s ago
 Main PID: 12484 (code=exited, status=1/FAILURE)

Apr 03 18:19:12 kn02fsc bash[12484]: Traceback (most recent call last):
Apr 03 18:19:12 kn02fsc bash[12484]:   File "ztp", line 3993, in <module>
Apr 03 18:19:12 kn02fsc bash[12484]:     interpreter()
Apr 03 18:19:12 kn02fsc bash[12484]:   File "ztp", line 3467, in interpreter
Apr 03 18:19:12 kn02fsc bash[12484]:     start_tftp()
Apr 03 18:19:12 kn02fsc bash[12484]:   File "ztp", line 3408, in start_tftp
Apr 03 18:19:12 kn02fsc bash[12484]:     import tftpy
Apr 03 18:19:12 kn02fsc bash[12484]: ImportError: No module named tftpy
Apr 03 18:19:12 kn02fsc systemd[1]: ztp.service: Main process exited, code=exited, status=1/FAILURE
Apr 03 18:19:12 kn02fsc systemd[1]: ztp.service: Failed with result 'exit-code'.

**Comment by joda666** [comment]
apt install python-tftpy

ztp.service - FreeZTP Service
   Loaded: loaded (/etc/systemd/system/ztp.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-03 18:41:31 CEST; 16ms ago
 Main PID: 12816 (bash)
    Tasks: 2 (limit: 2327)
   CGroup: /system.slice/ztp.service
           ├─12816 /bin/bash -c cd /bin; python ztp run
           └─12817 python ztp run
