### ISSUE TITLE
Help with python error

### ISSUE THREAD

**Issue by dchau360** [convergeone/freeztp#73]
I'm getting this error:

[root@ztp-cisco ~]# ztp set dhcpd INTERFACE-ETHO first-address 10.32.132.150
Traceback (most recent call last):
  File "/usr/bin/ztp", line 4093, in <module>
    interpreter()
  File "/usr/bin/ztp", line 3811, in interpreter
    config.set(sys.argv)
  File "/usr/bin/ztp", line 912, in set
    self.set_dhcpd(args)
  File "/usr/bin/ztp", line 1089, in set_dhcpd
    import netaddr
  File "/usr/lib/python2.7/site-packages/netaddr/__init__.py", line 18, in <module>
    from netaddr.core import (AddrConversionError, AddrFormatError,
  File "/usr/lib/python2.7/site-packages/netaddr/core.py", line 11, in <module>
    from netaddr.compat import _callable, _iter_dict_keys
  File "/usr/lib/python2.7/site-packages/netaddr/compat.py", line 93, in <module>
    import importlib_resources as _importlib_resources
  File "/usr/lib/python2.7/site-packages/importlib_resources/__init__.py", line 5, in <module>
    from ._common import (
  File "/usr/lib/python2.7/site-packages/importlib_resources/_common.py", line 9, in <module>
    from ._compat import (
  File "/usr/lib/python2.7/site-packages/importlib_resources/_compat.py", line 42, in <module>
    from zipp import Path as ZipPath  # type: ignore
ImportError: No module named zipp

**Comment by derek-shnosh** [comment]
Try installing the `zipp` module.

```bash
pip install zipp
```

**Comment by dchau360** [comment]
Thank you it worked.  Had to also do "pip install --upgrade pip" first.
